### ISSUE TITLE
QSWATMOD INPUT DATA FORMAT NEEDED

### ISSUE THREAD

**Issue by vikas2021cem1012** [spark-brc/QSWATMOD2-plugin#22]
Dear Friends;
Greetings!
I'm working on QSWATMOD plugin in QGIS. I need a sample file for streamflow.obd and modflow.obd. Please share it if anyone having this file. I need to prepare for my study area.
Thank you.
email:- 23d1234@iitb.ac.in

**Comment by spark-brc** [comment]
The current version reads the CSV file format. When your model folder (SWAT-MODFLOW) includes the file with the extension (*.obd.csv), then QSWATMOD will show the list of the files. Please check the sample files at the following link: https://github.com/spark-brc/QSWATMOD2-plugin/discussions/14. This issue is now closed.
